---
title: "acad_thesis"
output: html_document
date: "2023-03-28"
---

```{r}
library(dplyr)
library(tidyverse)
```

### Importing and cleaning data

```{r}
acad_data = read_csv(file = "./data/REDCAP.csv") %>%
  janitor::clean_names() 
  skimr::skim(acad_data)
```

The CSV file was downloaded from the ACAD dataset. The dataset `acad_data` has 327 observations and 660 variables. Of the 660 varaibles, 491 are character variables, 70 are logical, and 99 are numeric. The relevant variables were then selected for further cleaning.

```{r}
acad_clean = acad_data %>%
  select(
    "acad_id", "degree", "gender", "country_a", "generation", 
    
    "parta_a201", "parta_a202", "parta_a203", "parta_a204", "parta_a205", "parta_a206", "parta_a207", "parta_a208", "parta_a209", "parta_a210", "parta_a211", "parta_a212", "parta_a213", "parta_a214", "parta_a2score",
    
    "memory", "orient", "judgment", "commun", "homehobb", "perscare", "cdr_sum", "cdrglob", "comport", "cdrlang",
    
    "bills", "taxes", "shopping", "games", "stove", "mealprep", "events", "payattn", "remdates", "travel", "fas", 
    
    "clock1", "clock2", "clock3", "clock4", "clock5", "clock6", "clock7", "clock8", "clock9", "clock10", "clock11", "clock12", "clock13", "clock14", "clock15", "clock_t",
    
    "word1_t1", "word2_t1", "word3_t1", "word4_t1", "word5_t1", "word6_t1", "word7_t1", "word8_t1", "word9_t1", "word10_t1", "comt_t1","word1_t2", "word2_t2", "word3_t2", "word4_t2", "word5_t2", "word6_t2", "word7_t2", "word8_t2", "word9_t2", "word10_t2", "comt_t2", "word1_t3", "word2_t3", "word3_t3", "word4_t3", "word5_t3", "word6_t3", "word7_t3", "word8_t3", "word9_t3", "word10_t3", "comt_t3","word1_d", "word2_d", "word3_d", "word4_d", "word5_d", "word6_d", "word7_d", "word8_d", "word9_d", "word10_d", "comt_d", "item1", "item2", "item3", "item4", "item5", "item6", "item7", "item8", "item9", "item10", "word1_dr", "word2_dr", "word3_dr", "word4_dr", "word5_dr", "word6_dr", "word7_dr", "word8_dr","word9_dr", "word10_dr", "comt_dr",
    
    "condition1", "condition2", "condition3", "condition4", "condition5", "condition6", "condition7", "condition8", "condition9", "condition10", "condition11", "condition12", "condition13", "condition14", "condition15"
  ) %>%
  mutate(
    degree = factor(
      #age
      degree, levels = c("Grade school or less", 
                                       "Some high school", 
                                       "High school or G.E.D.", 
                                       "Graduate degree (Master's, Doctoral, or Professional degree)")),
    #gender
    country_a = as.character(country_a),
    country_a = recode(country_a, 
                       "156" = "China", 
                       "410" = "South Korea", 
                       "124" = "Canada", 
                       "344" = "Hong Kong", 
                       "158" = "Taiwan", 
                       "360" = "Indonesia", 
                       "458" = "Malaysia", 
                       "888" = "Other", 
                       "704" = "Vietnam" ),    
    generation = factor(generation, labels = c("1st", 
                                               "2nd", 
                                               "3rd", 
                                               "4th")),
    parta_a202 = recode(parta_a202,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a203 = recode(parta_a203,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a204 = recode(parta_a204,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a205 = recode(parta_a205,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a206 = recode(parta_a206,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a207 = recode(parta_a207,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a208 = recode(parta_a208,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a209 = recode(parta_a209,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a210 = recode(parta_a210,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a211 = recode(parta_a211,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a212 = recode(parta_a212,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a213 = recode(parta_a213,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a214 = recode(parta_a214,
                        "0 No" = 0,
                        "1 Yes" = 1),
    parta_a201 = ifelse(is.na(parta_a201), 0, parta_a201),
    parta_a202 = ifelse(is.na(parta_a202), 0, parta_a202),
    parta_a203 = ifelse(is.na(parta_a203), 0, parta_a203),
    parta_a204 = ifelse(is.na(parta_a204), 0, parta_a204),
    parta_a205 = ifelse(is.na(parta_a205), 0, parta_a205),
    parta_a206 = ifelse(is.na(parta_a206), 0, parta_a206),
    parta_a207 = ifelse(is.na(parta_a207), 0, parta_a207),
    parta_a208 = ifelse(is.na(parta_a208), 0, parta_a208),
    parta_a209 = ifelse(is.na(parta_a209), 0, parta_a209),
    parta_a210 = ifelse(is.na(parta_a210), 0, parta_a210),
    parta_a211 = ifelse(is.na(parta_a211), 0, parta_a211),
    parta_a212 = ifelse(is.na(parta_a212), 0, parta_a212),
    parta_a213 = ifelse(is.na(parta_a213), 0, parta_a213),
    parta_a214 = ifelse(is.na(parta_a214), 0, parta_a214),
    parta_a2score = parta_a201 + parta_a202 + parta_a203 + parta_a204 + parta_a205 + parta_a206 + parta_a207 + parta_a208 + parta_a209 + parta_a210 + parta_a211 + parta_a212 + parta_a213 + parta_a214,
    memory = recode(memory, 
                    "Moderate - 2 Severe memory loss; only highly learned material retained; new material rapidly lost." = 2),
    orient = recode(orient,
                    "None - 0 Fully oriented" = 0,
                    "Questionable - 0.5 Fully oriented except for slight difficulty with time relationships." = 0.5,
                    "Mild - 1 Moderate difficulty with time relationships; oriented for place at examination; may have geographic disorientation elsewhere." = 1,
                    "Moderate - 2 Severe difficulty with time relationships; usually disoriented to time, often to place." = 2,
                    "Severe - 3 Oriented to person only." = 3),
    judgment = recode(judgment,
                       "None - 0 Solves everyday problems, handles business & financial affairs well; judgment good in relation to past performance." = 0,
                      "Questionable - 0.5 Slight impairment in solving problems, similarities, and differences." = 0.5,
                      "Mild - 1 Moderate difficulty in handling problems, similarities, and differences; social judgment usually maintained." = 1,
                      "Moderate - 2 Severely impaired in handling problems, similarities, and differences; social judgment usually impaired." = 2,
                      "Severe - 3 Unable to make judgments or solve problems." = 3),
    commun = recode(commun,
                    "None - 0 Independent function at usual level in job, shopping, volunteer and social groups." = 0,
                    "Questionable - 0.5 Slight impairment in these activities." = 0.5,
                    "Mild - 1 Unable to function independently at these activities, although may still be engaged in some; appears normal to casual inspection." = 1,
                    "Moderate - 2 No pretense of independent function outside the home; appears well enough to be taken to functions outside the family home." = 2,
                    "Severe - 3 No pretense of independent function outside the home; appears too ill to be taken to functions outside the family home." = 3),
    homehobb = recode(homehobb,
                      "None - 0 Life at home, hobbies, and intellectual interests well maintained." = 0,
                      "Questionable - 0.5 Life at home, hobbies, and intellectual interests slightly impaired." = 0.5,
                      "Mild - 1 Mild but definite impairment of function at home; more difficult chores abandoned; more complicated hobbies and interests abandoned." = 1,
                      "Moderate - 2 Only simple chores preserved; very restricted interests, poorly maintained." = 2,
                      "Severe - 3 No significant function in the home." = 3),
    perscare = recode(perscare, 
                      "None / Questionable - 0Fully capable of self-care (=0)." = 0,
                      "0.5" = 0.5,
                      "Mild - 1 Needs prompting." = 1,
                      "Moderate - 2 Requires assistance in dressing, hygiene, keeping of personal effects." = 2,
                      "Severe - 3 Requires much help with personal care; frequent incontinence." = 3),
    memory = ifelse(is.na(memory), 0, memory),
    orient = ifelse(is.na(orient), 0, orient),
    judgment = ifelse(is.na(judgment), 0, judgment),
    commun = ifelse (is.na(commun), 0, commun),
    homehobb= ifelse(is.na(homehobb), 0, homehobb),
    perscare = ifelse(is.na(perscare), 0, perscare),
    cdr_sum = memory + orient + judgment + commun + homehobb + perscare,
    #cdrglob 
    comport = recode(comport,
                     "None - 0Socially appropriate behavior." = 0,
                     "Questionable - 0.5Questionable changes in comportment, empathy, appropriateness of actions." = 0.5,
                     "Mild - 1Mild but definite changes in behavior." = 1,
                     "Moderate - 2Moderate behavioral changes, affecting interpersonal relationships and interactions in a significant manner." = 2,
                     "Severe - 3Severe behavioral changes, making interpersonal interactions all unidirectional." = 3),
    cdrlang = recode(cdrlang,
                     "None - 0 No language difficulty or occasional mild tip-of-the-tongue." = 0,
                     "Questionable - 0.5Consistent mild word finding difficulties; simplification of word choice; circumlocution; decreased phrase length; and/or mild comprehension difficulties." = 0.5,
                     "Mild - 1Moderate word finding difficulty in speech; cannot name objects in environment; reduced phrase length and/or agrammatical speech; and/or reduced comprehension in conversation and reading." = 1,
                     "Moderate - 2Moderate to severe impairments in either speech or comprehension; has difficulty communicating thoughts; writing may be slightly more effective." = 2,
                     "Severe - 3Severe comprehension deficits; no intelligible speech." = 3),
    #functional assessment score variables (bills:fas)
    #clock1 variable 
    clock2 = recode(clock2, 
                    "No" = 0,
                    "Yes" = 1),
    clock3 = recode(clock3, 
                    "No" = 0,
                    "Yes" = 1),
    clock4 = recode(clock4, 
                    "No" = 0,
                    "Yes" = 1),
    clock5 = recode(clock5, 
                    "No" = 0,
                    "Yes" = 1),
    clock6 = recode(clock6, 
                    "No" = 0,
                    "Yes" = 1),
    clock7 = recode(clock7, 
                    "No" = 0,
                    "Yes" = 1),
    clock8 = recode(clock8, 
                    "No" = 0,
                    "Yes" = 1),
    clock9 = recode(clock9, 
                    "No" = 0,
                    "Yes" = 1),
    clock10 = recode(clock10, 
                    "No" = 0,
                    "Yes" = 1),
    clock11 = recode(clock11, 
                    "No" = 0,
                    "Yes" = 1),
    clock12 = recode(clock12, 
                    "No" = 0,
                    "Yes" = 1),
    clock13 = recode(clock13, 
                    "No" = 0,
                    "Yes" = 1),
    clock14 = recode(clock14, 
                    "No" = 0,
                    "Yes" = 1),
    clock15 = recode(clock15, 
                    "No" = 0,
                    "Yes" = 1),
    #clock_t score
    #word1_t1 variable
    word2_t1 = recode(word2_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word3_t1 = recode(word3_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word4_t1 = recode(word4_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word5_t1 = recode(word5_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word6_t1 = recode(word6_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word7_t1 = recode(word7_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word8_t1 = recode(word8_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word9_t1 = recode(word9_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word10_t1 = recode(word10_t1,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    #comt_t1
    #word8_t2
    word5_t2 = recode(word5_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word1_t2 = recode(word1_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word7_t2 = recode(word7_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word10_t2 = recode(word10_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word9_t2 = recode(word9_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word3_t2 = recode(word3_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word4_t2 = recode(word4_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word6_t2 = recode(word6_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    word2_t2 = recode(word2_t2,
                      "Inaccurate or required prompting for performance" = 0,
                      "Correctly recalled" = 1),
    #comt_t2
    word1_t3 = recode(word1_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word2_t3 = recode(word2_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    #word3_t3
    word4_t3 = recode(word4_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word5_t3 = recode(word5_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word6_t3 = recode(word6_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word7_t3 = recode(word7_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word8_t3 = recode(word8_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word9_t3 = recode(word9_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    word10_t3 = recode(word10_t3,
                      "Inaccurate or required prompting for performance." = 0,
                      "Correctly Recalled" = 1),
    #comt_t3
    #word1_d
    word2_d = recode(word2_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word3_d = recode(word3_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word4_d = recode(word4_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word5_d = recode(word5_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word6_d = recode(word6_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word7_d = recode(word7_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word8_d = recode(word8_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word9_d = recode(word9_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    word10_d = recode(word10_d,
                     "inaccurate or required prompting for performance" = 0,
                     "Correctly recalled" = 1),
    #comt_d
    #item1
    item2 = recode(item2, 
                   "No" = 0,
                   "Yes" = 1),
    item3 = recode(item3, 
                   "No" = 0,
                   "Yes" = 1),
    item4 = recode(item4, 
                   "No" = 0,
                   "Yes" = 1),
    item5 = recode(item5, 
                   "No" = 0,
                   "Yes" = 1),
    item6 = recode(item6, 
                   "No" = 0,
                   "Yes" = 1),
    item7 = recode(item7, 
                   "No" = 0,
                   "Yes" = 1),
    item8 = recode(item8, 
                   "No" = 0,
                   "Yes" = 1),
    item9 = recode(item9, 
                   "No" = 0,
                   "Yes" = 1),
    item10 = recode(item10, 
                   "No" = 0,
                   "Yes" = 1),
    word1_dr = recode(word1_dr,
                      "No" = 0,
                      "Yes" = 1),
    word2_dr = recode(word2_dr,
                      "No" = 0,
                      "Yes" = 1),
    word3_dr = recode(word3_dr,
                      "No" = 0,
                      "Yes" = 1),
    word4_dr = recode(word4_dr,
                      "No" = 0,
                      "Yes" = 1),
    word5_dr = recode(word5_dr,
                      "No" = 0,
                      "Yes" = 1),
    word6_dr = recode(word6_dr,
                      "No" = 0,
                      "Yes" = 1),
    word7_dr = recode(word7_dr,
                      "No" = 0,
                      "Yes" = 1),
    word8_dr = recode(word8_dr,
                      "No" = 0,
                      "Yes" = 1),
    word9_dr = recode(word9_dr,
                      "No" = 0,
                      "Yes" = 1),
    word10_dr = recode(word10_dr,
                      "No" = 0,
                      "Yes" = 1),
    #comt_dr
    condition1 = recode(condition1,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),

    condition2 = recode(condition2,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition3 = recode(condition3,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition4 = recode(condition4,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition5 = recode(condition5,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition6 = recode(condition6,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition7 = recode(condition7,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition8 = recode(condition8,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition9 = recode(condition9,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition10 = recode(condition10,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition11 = recode(condition11,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition12 = recode(condition12,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition13 = recode(condition13,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55),
    condition14 = recode(condition14,
                        "No" = 0,
                        "Yes" = 1,
                        "Don't know (Unsure)" = 55)
    )

```


    


 

    




